# SITE CONFIGURATION
#baseurl: "/Type-on-Strap"
url: "https://apjena.github.io"

#theme: type-on-strap                                  # if using the theme as a jekyll theme gem
#remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
remote_theme: allejo/jekyll-docs-theme@v1.0.0


# META AND BRANDING
title: "Thought &#120511;"                         # site's title
description: "Waves of Thoughts"                         # used by search engines
avatar: assets/img/avtar.png #triangle.png         # Empty for no avatar in navbar
favicon: assets/favicon.ico                        # Icon displayed in the tab
color_theme: auto                                  # auto | dark | light

