#remote_theme: pages-themes/slate@v0.2.0
#remote_theme: pages-themes/tactile@v0.2.0
#remote_theme: pages-themes/modernist@v0.2.0
#remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: pages-themes/midnight@v0.2.0
#remote_theme: pages-themes/leap-day@v0.2.0
#remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
remote_theme: sylhare/Type-on-Strap
theme_settings:
  katex: true # to Enable it
  mathjax: true 
relative_links:
  enabled: true 
  collections: true 
# For github inbuilt themes instead:
#theme: jekyll-theme-minimal  
# architect cayman dinky hacker leap-day merlot
# midnight minimal minimal modernist 
# slate tactile time-machine 
#title: Wave of Thoughts
#description: 
include:
  - ['_pages']
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
menu:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/
show_downloads: false 
github:
  is_project_page: false 
# These settings control how pages and collections are included in the site
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
