title: Wave of Thoughts
description: ME WITH YOU.
baseurl: ""
url: "apjena.github.io"
repository: 
paginate: 28

<<<<<<< HEAD
#remote_theme: sylhare/Type-on-Strap
#remote_theme: barryclark/jekyll-now
#remote_theme: sighingnow/jekyll-gitbook
#remote_theme: minimal-mistakes-jekyll
#remote_theme: "mmistakes/minimal-mistakes@4.27.3"
#remote_theme: chauff/cse-theme
#remote_theme: alshedivat/al-folio
=======
banner: "/assets/res/banner.png" # site banner (load when someone share your page url)
favicon: "/assets/res/favicon.png" # site's favicon (icon left side of your page)

# MatJek specific configurations
user: 
  name: "APJ"
  email: "dinhanhthimail@gmail.com"
  website: "math2it.com"
  avatar: "/assets/res/user.png"
  github: "apjena"
google_tracking_id: ""
google_site_verification: ""
disqus_shortname: this-site

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title

>>>>>>> 1249c19 (18.12No1)

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

<<<<<<< HEAD
# Blog
#excerpt: false                                           # Or "truncate" (first 250 characters), "false" to disable
#post_navigation: true
#color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for comments, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
#katex: true                                             # Enable if using math markup
#mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
#google_analytics:                                       # Measurement ID, e.g. "G-00000"
#cookie_consent: false                                   # To respect the usage of cookies
#color_theme: auto      # auto, dark or light
#gitbook theme supported declarations:
toc:      
    enabled: true
    h_min: 1
    h_max: 3
collections:
  pages:
    output: true
    sort_by: date
    permalink: /:collection/:year-:month-:day-:title:output_ext
  others:
    output: true
    sort_by: date
    permalink: /:collection/:year-:month-:day-:title:output_ext

ordered_collections:
  - posts
  - pages
  - others

# PAGINATION
#paginate: 5
#paginate_path: "/blog/page:num"

# PORTFOLIO
#collections:
#  portfolio:
#    output: true
 #   permalink: /:collection/:name

# BUILD SETTINGS
#sass:
#  style: compressed
#  quiet_deps: true
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*", ".github/*"]


# For github inbuilt themes instead:
theme: jekyll-theme-cayman  # other options below:
# architect cayman dinky hacker leap-day merlot
# midnight minimal minimal modernist 
=======
  future: true
>>>>>>> 1249c19 (18.12No1)
