# SITE CONFIGURATION
#baseurl: "/Type-on-Strap"
url: "https://apjena.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Waves of Thoughts                                   # site's title
description: "me with you"                              # used by search engines
avatar: assets/img/avtar.png #triangle.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_pages: 
 - about.md
header_text: Change <code>header_text</code> in <code>_config.yml</code>  # Change Blog header text
header_feature_image: assets/img/header/headerbanner.jpg         #assets/img/header/triangular.jpeg
#header_feature_image_responsive: true
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> based on <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a> theme and proudly hosted on <a href="https://github.com">GitHub</a>.

# Blog
excerpt: false                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for comments, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true           # Enable if using math markup
mermaid: default      # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics:         # Measurement ID, e.g. "G-00000"
cookie_consent: false     # To respect the usage of cookies
color_theme: auto         # auto, dark or light

# PAGINATION
paginate: 5
#paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
#sass:
#  style: compressed
#  quiet_deps: true
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*", ".github/*"]

